"""add tables

Revision ID: ef876a8cd302
Revises: 
Create Date: 2020-11-26 23:13:43.933511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef876a8cd302'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('url_collection_idx_url', 'url_collection', ['url'], unique=True)
    op.create_table('word_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=400), nullable=True),
    sa.Column('is_filtered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('word_collection_idx_day_room', 'word_collection', ['word'], unique=True)
    op.create_table('link_between_url_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_from_id', sa.Integer(), nullable=True),
    sa.Column('url_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['url_from_id'], ['url_collection.id'], ),
    sa.ForeignKeyConstraint(['url_to_id'], ['url_collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_location_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('url_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['url_collection.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word_collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link_word_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('between_url_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['between_url_id'], ['link_between_url_collection.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word_collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_word_collection')
    op.drop_table('word_location_collection')
    op.drop_table('link_between_url_collection')
    op.drop_index('word_collection_idx_day_room', table_name='word_collection')
    op.drop_table('word_collection')
    op.drop_index('url_collection_idx_url', table_name='url_collection')
    op.drop_table('url_collection')
    # ### end Alembic commands ###
